version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          path: .
          platform: linux/amd64
          push-image: true
          region: eu-north-1
          repo: end-to-end-nlp-project
          registry-id: 261431661667
          repo-scan-on-push: true
          tag: latest

  continuous-delivery:
    machine: true
    resource_class: ghulam/end-to-end-nlp-project
    steps:
      - aws-cli/setup

      - run:
          name: Authenticate to AWS ECR (Stockholm)
          command: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 261431661667.dkr.ecr.eu-north-1.amazonaws.com
          
      - run:
          name: Pull image from private ECR repository
          command: docker pull 261431661667.dkr.ecr.eu-north-1.amazonaws.com/end-to-end-nlp-project:latest
          
      - run:
          name: Run container from pulled image
          command: docker run -d -p 8080:8080 261431661667.dkr.ecr.eu-north-1.amazonaws.com/end-to-end-nlp-project:latest

workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration



      
